export const PROFILE_MOUSE_OVER = 'PROFILE_MOUSE_OVER';
export const PROFILE_MOUSE_OUT = 'PROFILE_MOUSE_OUT';
export const MAIN_MENU_MOUSE_OVER = 'MAIN_MENU_MOUSE_OVER';
export const MAIN_MENU_MOUSE_OUT = 'MAIN_MENU_MOUSE_OUT';